on: push
jobs:
  oracle9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make
      - run: sudo gem install package_cloud
      - run: package_cloud push vassilevsky/artipie/ol/9 ~/rpmbuild/RPMS/noarch/*.rpm
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
