on: push
jobs:
  oracle9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make
      - run: gem install package_cloud
      - run: package_cloud push vassilevsky/artipie ~/rpmbuild/RPMS/noarch
