on: push
jobs:
  oracle9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: wget https://github.com/artipie/artipie/releases/download/v0.28.0/artipie-v0.28.0-jar-with-dependencies.jar -O artipie.jar
      - run: rpmbuild -bb --build-in-place artipie.spec
      - uses: danielmundi/upload-packagecloud@v1
        with:
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
          packagecloud-username: vassilevsky
          packagecloud-repo: artipie
          packagecloud-distrib: ol/9
          package-name: /home/runner/rpmbuild/RPMS/noarch/artipie-0.28.0-4.noarch.rpm
